import { MigrationInterface, QueryRunner } from 'typeorm'

export class ProductAutoGeneratedUUID1718304389598
  implements MigrationInterface
{
  // Caminho feliz
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
      `)

    await queryRunner.query(`
      ALTER TABLE product
      ALTER COLUMN id SET DEFAULT uuid_generate_v4();
      `)
  }

  // Caso aconteça algum erro
  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      ALTER TABLE product
      ALTER COLUMN id DROP DEFAULT;
      `)
  }
}
