import { DataSource } from 'typeorm'
import { env } from '@/env'
import { Product } from '@/entities/product.entity'
import { Category } from '@/entities/category.entity'
import { ProductAutoGeneratedUUID1718304389598 } from './migrations/1718304389598-ProductAutoGeneratedUUID'

export const appDataSource = new DataSource({
  type: 'postgres',
  host: env.DATABASE_HOST,
  port: env.DATABASE_PORT,
  username: env.DATABASE_USER,
  password: env.DATABASE_PASSWORD,
  database: env.DATABASE_NAME,
  entities: [Product, Category],
  // entities: ['src/entities/*.ts']  Você pode passar o caminho em vez da classe
  // mas dessa forma usando o "*.ts" ele vai pegar todos os arquivos .ts da pasta "entities"
  migrations: [ProductAutoGeneratedUUID1718304389598],
  logging: env.NODE_ENV === 'development',
})

appDataSource
  .initialize()
  .then(() => {
    console.log('Database with typeorm connected')
  })
  .catch((error) => {
    console.error('Error connecting to database with typeorm', error)
  })
